pipeline {
    agent {
        docker {
            image "python"
        }
    }

    stages {
        stage('Preparation') {
            steps {
                sh 'curl -fsSL https://deb.nodesource.com/setup_14.x | bash -'
                sh 'apt-get install -y xvfb ca-certificates net-tools netcat gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2 chromium chromium-chromedriver'
                sh 'apt-get install -y nodejs'
            }
        }

        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'rfbrowser init'
            }
        }

        stage('Test') {
            steps {
                sh 'robot -d logs -v HEADLESS:true tests/'
            }
        }

        stage('Deploy') {
            steps {
                sh 'Testing completed'
            }
        }
    }
}